first try
cheptsova/banda-ice-cream pull request #19
Opened 2023-01-13 19:48 UTC by ZloStyle

tried my best, waiting for the review.

2023-01-13 19:50 UTC, ZloStyle commented
first try

2023-01-13 20:24 UTC, cheptsova requested changes
Request changes

2023-01-13 21:52 UTC, cheptsova requested changes
Request changes

2023-01-14 13:05 UTC, cheptsova approved these changes
fix in new branch 786 px background picture

2023-01-14 13:05 UTC, merged